FROM quay.io/fedora/fedora@sha256:1972716109b1c906120061063bd4cb50a46c2138d95002ccb90126928d98e013

ENV SUMMARY="Thoth's toolchain for running pre-commit hooks." \
    DESCRIPTION="This is part of Thoth's toolchain for running pre-commit hooks, and it is supposed to run as a Prow presubmit job."

LABEL maintainer="Christoph Görn <goern@b4mad.net>"

ENV PATH=$HOME/.local/bin/:$PATH \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    LC_ALL=C_US.UTF-8 \
    LANG=C_US.UTF-8 \
    PIP_NO_CACHE_DIR=off

LABEL summary="$SUMMARY" \
    description="$DESCRIPTION" \
    io.k8s.description="$DESCRIPTION" \
    io.k8s.display-name="Thoth Pre-Commit" \
    io.openshift.tags="pre-commit" \
    name="thoth-station/pre-commit" \
    version="0.17.0"

RUN dnf update -y \
        --setopt=tsflags=nodocs && \
    dnf install -y \
        --setopt=tsflags=nodocs \
        --setopt=deltarpm=false \
        findutils \
        python3.10-devel \
        python3-pip \
        gcc \
        gcc-c++ \
        git-core \
        make && \
    dnf clean all
RUN pip install --no-cache-dir pre-commit

ADD prow-job-precommit /usr/bin

WORKDIR /src

CMD ["/usr/bin/prow-job-precommit"]
